export const PROGRESS_UPLOAD = "PROGRESS_UPLOAD"
export const PROGRESS_DOWNLOAD = "PROGRESS_DOWNLOAD"
export const CLEAR_PROGRESS = "CLEAR_PROGRESS"

export default {
  PROGRESS_UPLOAD,
  PROGRESS_DOWNLOAD,
  CLEAR_PROGRESS,
}
